# Generated by Django 4.1.5 on 2023-02-06 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer_city_customer_phonenumber_customer_street_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='postcode',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
