# Generated by Django 4.1.5 on 2023-02-06 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_name_customer_first_name_customer_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
