# Generated by Django 4.1.5 on 2023-02-07 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_product_digital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='state',
            new_name='postcode',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zipcode',
            new_name='street',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='suburb',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
